{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "bulletin-board.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
    name: {{ .Values.externalSecret.secretStoreRef.name }}
  target:
    name: {{ .Values.names.secret }}
    creationPolicy: {{ .Values.externalSecret.creationPolicy }}
  dataFrom:
    - extract:
        key: {{ required "externalSecret.remoteRef.secretId is required" .Values.externalSecret.remoteRef.secretId | quote }}
{{- end }}
