apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://rc1a-3gm7be5l0ehi2vn6.mdb.yandexcloud.net:6432/bulletins"
  MANAGEMENT_SERVER_PORT: "9090"
  SPRING_PROFILES_ACTIVE: "prod"
