apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: yandex-lockbox
spec:
  provider:
    yandexlockbox:
      auth:
        authorizedKeySecretRef:
          name: yandex-lockbox-sa-key
          namespace: external-secrets
          key: authorized-key
